-- MySQL Script generated by MySQL Workbench
-- dom 20 mar 2022 14:28:39
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_jornal
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `db_jornal` ;

-- -----------------------------------------------------
-- Schema db_jornal
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_jornal` DEFAULT CHARACTER SET utf8 ;
USE `db_jornal` ;

-- -----------------------------------------------------
-- Table `Categoria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `categoria` ;

CREATE TABLE IF NOT EXISTS `categoria` (
  `id_categoria` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `desc` VARCHAR(45) NULL,
  PRIMARY KEY (`id_categoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Comentarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `comentarios` ;

CREATE TABLE IF NOT EXISTS `comentarios` (
  `id_comentarios` INT NOT NULL AUTO_INCREMENT,
  `conteudo` TEXT NOT NULL,
  `data_coment` DATETIME NOT NULL,
  `Postagens_id_postagens` INT NOT NULL,
  `Usuarios_id_usuarios` INT NOT NULL,
  PRIMARY KEY (`id_comentarios`),
  INDEX `fk_Comentarios_Postagens1_idx` (`postagens_id_postagens` ASC),
  INDEX `fk_Comentarios_Usuarios1_idx` (`usuarios_id_usuarios` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Postagens`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `postagens` ;

CREATE TABLE IF NOT EXISTS `postagens` (
  `id_postagens` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(255) NOT NULL,
  `imagem` VARCHAR(255) NOT NULL,
  `conteudo` TEXT NOT NULL,
  `data_post` DATETIME NOT NULL,
  `Usuarios_id_usuarios` INT NOT NULL,
  `Categoria_id_categoria` INT NOT NULL,
  PRIMARY KEY (`id_postagens`),
  INDEX `fk_Postagens_Usuarios_idx` (`Usuarios_id_usuarios` ASC),
  INDEX `fk_Postagens_Categoria1_idx` (`Categoria_id_categoria` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `usuarios` ;

CREATE TABLE IF NOT EXISTS `usuarios` (
  `id_usuarios` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  `adm` INT NOT NULL DEFAULT 0,
  `email` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_usuarios`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
