-- MySQL Script generated by MySQL Workbench
-- Tue Mar 22 15:15:10 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Projecto_clever
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Projecto_clever
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Projecto_clever` DEFAULT CHARACTER SET utf8 ;
USE `Projecto_clever` ;

-- -----------------------------------------------------
-- Table `Projecto_clever`.`Monografia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Projecto_clever`.`Monografia` (
  `idMonografia` INT NOT NULL AUTO_INCREMENT,
  `trabalho` LONGTEXT NOT NULL,
  `data` DATE NOT NULL,
  PRIMARY KEY (`idMonografia`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Projecto_clever`.`Estagio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Projecto_clever`.`Estagio` (
  `idEstagio` INT NOT NULL AUTO_INCREMENT,
  `actividade` VARCHAR(255) NOT NULL,
  `relatorio` LONGTEXT NOT NULL,
  `duracao` VARCHAR(50) NOT NULL,
  `inicio` DATE NOT NULL,
  `fim` DATE NOT NULL,
  `nota` INT NOT NULL,
  PRIMARY KEY (`idEstagio`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Projecto_clever`.`Local_empresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Projecto_clever`.`Local_empresa` (
  `idLocal_empresa` INT NOT NULL AUTO_INCREMENT,
  `Pais` VARCHAR(255) NOT NULL DEFAULT 'Angola',
  `endereco` TEXT NOT NULL,
  `modified` DATE NOT NULL,
  PRIMARY KEY (`idLocal_empresa`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Projecto_clever`.`Empresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Projecto_clever`.`Empresa` (
  `idEmpresa` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `actividade` VARCHAR(255) NOT NULL,
  `contacto` VARCHAR(20) NOT NULL,
  `Email` VARCHAR(100) NOT NULL,
  `idLocal_empresa_foren` INT NOT NULL,
  PRIMARY KEY (`idEmpresa`),
  UNIQUE INDEX `nome_UNIQUE` (`nome` ASC) VISIBLE,
  INDEX `fk_Empresa_Local_empresa1_idx` (`idLocal_empresa_foren` ASC) VISIBLE,
  CONSTRAINT `fk_Empresa_Local_empresa1`
    FOREIGN KEY (`idLocal_empresa_foren`)
    REFERENCES `Projecto_clever`.`Local_empresa` (`idLocal_empresa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Projecto_clever`.`Supervisor_estagio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Projecto_clever`.`Supervisor_estagio` (
  `idSupervisor_estagio` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `idade` DATE NOT NULL,
  `sexo` ENUM('M', 'F') NOT NULL,
  `nacionalidade` VARCHAR(255) NOT NULL,
  `contacto` VARCHAR(20) NOT NULL,
  `endereco` TEXT NOT NULL,
  PRIMARY KEY (`idSupervisor_estagio`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Projecto_clever`.`Curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Projecto_clever`.`Curso` (
  `idCurso` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `descricao` TEXT NOT NULL,
  PRIMARY KEY (`idCurso`),
  UNIQUE INDEX `nome_UNIQUE` (`nome` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Projecto_clever`.`Usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Projecto_clever`.`Usuarios` (
  `idUsuarios` INT ZEROFILL NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(255) NOT NULL,
  `senha` VARCHAR(15) NOT NULL,
  `nivel` INT NULL DEFAULT 0,
  PRIMARY KEY (`idUsuarios`),
  UNIQUE INDEX `email_UNIQUE` (`login` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Projecto_clever`.`Estudante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Projecto_clever`.`Estudante` (
  `idEstudante` INT ZEROFILL NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `idade` DATE NOT NULL,
  `sexo` ENUM('M', 'F') NOT NULL DEFAULT 'M',
  `nacionalidade` VARCHAR(255) NOT NULL DEFAULT 'Angolana',
  `matricula` VARCHAR(255) NOT NULL,
  `Encarregado` VARCHAR(255) NOT NULL,
  `contacto` VARCHAR(20) NOT NULL,
  `endereco` TEXT NOT NULL,
  `idMonografia_foren` INT NULL,
  `idEstagio_foren` INT NOT NULL,
  `idSupervisor_estagio_foren` INT NOT NULL,
  `idCurso_foren` INT NOT NULL,
  `Usuarios_idUsuarios` INT ZEROFILL NOT NULL,
  PRIMARY KEY (`idEstudante`),
  INDEX `fk_Estudante_Monografia1_idx` (`idMonografia_foren` ASC) VISIBLE,
  INDEX `fk_Estudante_Estagio1_idx` (`idEstagio_foren` ASC) VISIBLE,
  INDEX `fk_Estudante_Supervisor_estagio1_idx` (`idSupervisor_estagio_foren` ASC) VISIBLE,
  INDEX `fk_Estudante_Curso1_idx` (`idCurso_foren` ASC) VISIBLE,
  INDEX `fk_Estudante_Usuarios1_idx` (`Usuarios_idUsuarios` ASC) VISIBLE,
  CONSTRAINT `fk_Estudante_Monografia1`
    FOREIGN KEY (`idMonografia_foren`)
    REFERENCES `Projecto_clever`.`Monografia` (`idMonografia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Estudante_Estagio1`
    FOREIGN KEY (`idEstagio_foren`)
    REFERENCES `Projecto_clever`.`Estagio` (`idEstagio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Estudante_Supervisor_estagio1`
    FOREIGN KEY (`idSupervisor_estagio_foren`)
    REFERENCES `Projecto_clever`.`Supervisor_estagio` (`idSupervisor_estagio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Estudante_Curso1`
    FOREIGN KEY (`idCurso_foren`)
    REFERENCES `Projecto_clever`.`Curso` (`idCurso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Estudante_Usuarios1`
    FOREIGN KEY (`Usuarios_idUsuarios`)
    REFERENCES `Projecto_clever`.`Usuarios` (`idUsuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Projecto_clever`.`Tutor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Projecto_clever`.`Tutor` (
  `idTutor` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `idade` VARCHAR(255) NOT NULL,
  `nacionalidade` VARCHAR(255) NOT NULL,
  `Especialidade` VARCHAR(255) NOT NULL,
  `contacto` VARCHAR(20) NOT NULL,
  `endereco` TEXT NOT NULL,
  `sexo` ENUM('M', 'F') NOT NULL DEFAULT 'M',
  `Usuarios_idUsuarios` INT ZEROFILL NOT NULL,
  PRIMARY KEY (`idTutor`),
  INDEX `fk_Tutor_Usuarios1_idx` (`Usuarios_idUsuarios` ASC) VISIBLE,
  CONSTRAINT `fk_Tutor_Usuarios1`
    FOREIGN KEY (`Usuarios_idUsuarios`)
    REFERENCES `Projecto_clever`.`Usuarios` (`idUsuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Projecto_clever`.`Estudante_has_Tutor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Projecto_clever`.`Estudante_has_Tutor` (
  `Estudante_idEstudante` INT NOT NULL,
  `Tutor_idTutor` INT NOT NULL,
  PRIMARY KEY (`Estudante_idEstudante`, `Tutor_idTutor`),
  INDEX `fk_Estudante_has_Tutor_Tutor1_idx` (`Tutor_idTutor` ASC) VISIBLE,
  INDEX `fk_Estudante_has_Tutor_Estudante_idx` (`Estudante_idEstudante` ASC) VISIBLE,
  CONSTRAINT `fk_Estudante_has_Tutor_Estudante`
    FOREIGN KEY (`Estudante_idEstudante`)
    REFERENCES `Projecto_clever`.`Estudante` (`idEstudante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Estudante_has_Tutor_Tutor1`
    FOREIGN KEY (`Tutor_idTutor`)
    REFERENCES `Projecto_clever`.`Tutor` (`idTutor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Projecto_clever`.`Estagio_has_Empresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Projecto_clever`.`Estagio_has_Empresa` (
  `Estagio_idEstagio` INT NOT NULL,
  `Empresa_idEmpresa` INT NOT NULL,
  PRIMARY KEY (`Estagio_idEstagio`, `Empresa_idEmpresa`),
  INDEX `fk_Estagio_has_Empresa_Empresa1_idx` (`Empresa_idEmpresa` ASC) VISIBLE,
  INDEX `fk_Estagio_has_Empresa_Estagio1_idx` (`Estagio_idEstagio` ASC) VISIBLE,
  CONSTRAINT `fk_Estagio_has_Empresa_Estagio1`
    FOREIGN KEY (`Estagio_idEstagio`)
    REFERENCES `Projecto_clever`.`Estagio` (`idEstagio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Estagio_has_Empresa_Empresa1`
    FOREIGN KEY (`Empresa_idEmpresa`)
    REFERENCES `Projecto_clever`.`Empresa` (`idEmpresa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
