-- MySQL Script generated by MySQL Workbench
-- dom 08 mai 2022 18:17:04
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Projecto_clever
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Projecto_clever
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Projecto_clever` DEFAULT CHARACTER SET utf8 ;
USE `Projecto_clever` ;

-- -----------------------------------------------------
-- Table `Usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Usuarios` ;

CREATE TABLE IF NOT EXISTS `Usuarios` (
  `idUsuarios` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(255) NOT NULL,
  `senha` VARCHAR(15) NOT NULL,
  `nivel` INT NULL DEFAULT 0,
  PRIMARY KEY (`idUsuarios`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `email_UNIQUE` ON `Usuarios` (`login` ASC);


-- -----------------------------------------------------
-- Table `Tutor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Tutor` ;

CREATE TABLE IF NOT EXISTS `Tutor` (
  `idTutor` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `Especialidade` VARCHAR(255) NOT NULL,
  `contacto` VARCHAR(20) NOT NULL,
  `endereco` TEXT NOT NULL,
  `email` VARCHAR(255) NOT NULL DEFAULT 'M',
  `Usuarios_idUsuarios` INT NOT NULL,
  PRIMARY KEY (`idTutor`, `Usuarios_idUsuarios`),
  CONSTRAINT `fk_Tutor_Usuarios1`
    FOREIGN KEY (`Usuarios_idUsuarios`)
    REFERENCES `Usuarios` (`idUsuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Tutor_Usuarios1_idx` ON `Tutor` (`Usuarios_idUsuarios` ASC);


-- -----------------------------------------------------
-- Table `membros_banca`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `membros_banca` ;

CREATE TABLE IF NOT EXISTS `membros_banca` (
  `id` INT NOT NULL,
  `nome` VARCHAR(255) NOT NULL,
  `contacto` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `Tutor_idTutor` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_membros_banca_Tutor1`
    FOREIGN KEY (`Tutor_idTutor`)
    REFERENCES `Tutor` (`idTutor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_membros_banca_Tutor1_idx` ON `membros_banca` (`Tutor_idTutor` ASC);


-- -----------------------------------------------------
-- Table `banca`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `banca` ;

CREATE TABLE IF NOT EXISTS `banca` (
  `idbanca` INT NOT NULL,
  `classificacao` VARCHAR(45) NOT NULL,
  `data_realizada` DATE NOT NULL,
  `num_banca` VARCHAR(45) NULL,
  `membros_banca_id` INT NOT NULL,
  PRIMARY KEY (`idbanca`, `membros_banca_id`),
  CONSTRAINT `fk_banca_membros_banca1`
    FOREIGN KEY (`membros_banca_id`)
    REFERENCES `membros_banca` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_banca_membros_banca1_idx` ON `banca` (`membros_banca_id` ASC);


-- -----------------------------------------------------
-- Table `Curso`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Curso` ;

CREATE TABLE IF NOT EXISTS `Curso` (
  `idCurso` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `descricao` TEXT NOT NULL,
  PRIMARY KEY (`idCurso`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `nome_UNIQUE` ON `Curso` (`nome` ASC);


-- -----------------------------------------------------
-- Table `Aluno`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Aluno` ;

CREATE TABLE IF NOT EXISTS `Aluno` (
  `idAluno` INT ZEROFILL NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `Ano_nasc` DATE NOT NULL,
  `sexo` ENUM('M', 'F') NOT NULL DEFAULT 'M',
  `Encarregado` VARCHAR(255) NOT NULL,
  `contacto` VARCHAR(255) NOT NULL,
  `Morada` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NULL,
  `Tutor_idTutor` INT NOT NULL,
  `Usuarios_idUsuarios` INT NOT NULL,
  `Curso_idCurso` INT NOT NULL,
  PRIMARY KEY (`idAluno`),
  CONSTRAINT `fk_Aluno_Tutor1`
    FOREIGN KEY (`Tutor_idTutor`)
    REFERENCES `Tutor` (`idTutor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Aluno_Usuarios1`
    FOREIGN KEY (`Usuarios_idUsuarios`)
    REFERENCES `Usuarios` (`idUsuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Aluno_Curso1`
    FOREIGN KEY (`Curso_idCurso`)
    REFERENCES `Curso` (`idCurso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Aluno_Tutor1_idx` ON `Aluno` (`Tutor_idTutor` ASC);

CREATE INDEX `fk_Aluno_Usuarios1_idx` ON `Aluno` (`Usuarios_idUsuarios` ASC);

CREATE INDEX `fk_Aluno_Curso1_idx` ON `Aluno` (`Curso_idCurso` ASC);


-- -----------------------------------------------------
-- Table `Defesas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Defesas` ;

CREATE TABLE IF NOT EXISTS `Defesas` (
  `idDefesas` INT NOT NULL,
  PRIMARY KEY (`idDefesas`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Monografia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Monografia` ;

CREATE TABLE IF NOT EXISTS `Monografia` (
  `idMonografia` INT NOT NULL AUTO_INCREMENT,
  `data_Entrega` DATE NOT NULL,
  `trabalho` VARCHAR(100) NOT NULL,
  `modificado` DATE NOT NULL,
  `banca_idbanca` INT NOT NULL,
  `banca_membros_id` INT NOT NULL,
  `tema` VARCHAR(255) NOT NULL,
  `Aluno_idAluno` INT ZEROFILL NOT NULL,
  `Defesas_idDefesas` INT NOT NULL,
  PRIMARY KEY (`idMonografia`, `Aluno_idAluno`),
  CONSTRAINT `fk_Monografia_banca1`
    FOREIGN KEY (`banca_idbanca` , `banca_membros_id`)
    REFERENCES `banca` (`idbanca` , `membros_banca_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Monografia_Aluno1`
    FOREIGN KEY (`Aluno_idAluno`)
    REFERENCES `Aluno` (`idAluno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Monografia_Defesas1`
    FOREIGN KEY (`Defesas_idDefesas`)
    REFERENCES `Defesas` (`idDefesas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Monografia_banca1_idx` ON `Monografia` (`banca_idbanca` ASC, `banca_membros_id` ASC);

CREATE UNIQUE INDEX `tema_UNIQUE` ON `Monografia` (`tema` ASC);

CREATE INDEX `fk_Monografia_Aluno1_idx` ON `Monografia` (`Aluno_idAluno` ASC);

CREATE INDEX `fk_Monografia_Defesas1_idx` ON `Monografia` (`Defesas_idDefesas` ASC);


-- -----------------------------------------------------
-- Table `Supervisor_estagio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Supervisor_estagio` ;

CREATE TABLE IF NOT EXISTS `Supervisor_estagio` (
  `idSupervisor_estagio` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `idade` DATE NOT NULL,
  `sexo` ENUM('M', 'F') NOT NULL,
  `nacionalidade` VARCHAR(255) NOT NULL,
  `contacto` VARCHAR(20) NOT NULL,
  `endereco` TEXT NOT NULL,
  PRIMARY KEY (`idSupervisor_estagio`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Empresa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Empresa` ;

CREATE TABLE IF NOT EXISTS `Empresa` (
  `idEmpresa` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `actividade` VARCHAR(255) NOT NULL,
  `contacto` VARCHAR(20) NOT NULL,
  `Email` VARCHAR(255) NOT NULL,
  `Localizacao` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idEmpresa`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `nome_UNIQUE` ON `Empresa` (`nome` ASC);


-- -----------------------------------------------------
-- Table `Estagio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Estagio` ;

CREATE TABLE IF NOT EXISTS `Estagio` (
  `idEstagio` INT NOT NULL AUTO_INCREMENT,
  `duracao` VARCHAR(50) NOT NULL,
  `data_inicio` DATE NOT NULL,
  `data_fim` DATE NOT NULL,
  `categoria` VARCHAR(255) NOT NULL,
  `Aluno_idEstudante` INT ZEROFILL NOT NULL,
  `idSupervisor_estagio` INT NOT NULL,
  `Empresa_idEmpresa` INT NOT NULL,
  PRIMARY KEY (`idEstagio`),
  CONSTRAINT `fk_Estagio_Aluno`
    FOREIGN KEY (`Aluno_idEstudante`)
    REFERENCES `Aluno` (`idAluno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Estagio_Supervisor_estagio1`
    FOREIGN KEY (`idSupervisor_estagio`)
    REFERENCES `Supervisor_estagio` (`idSupervisor_estagio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Estagio_Empresa1`
    FOREIGN KEY (`Empresa_idEmpresa`)
    REFERENCES `Empresa` (`idEmpresa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Estagio_Aluno_idx` ON `Estagio` (`Aluno_idEstudante` ASC);

CREATE INDEX `fk_Estagio_Supervisor_estagio1_idx` ON `Estagio` (`idSupervisor_estagio` ASC);

CREATE INDEX `fk_Estagio_Empresa1_idx` ON `Estagio` (`Empresa_idEmpresa` ASC);


-- -----------------------------------------------------
-- Table `Relatorios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Relatorios` ;

CREATE TABLE IF NOT EXISTS `Relatorios` (
  `idRelatorios` INT NOT NULL,
  `descricao` VARCHAR(255) NOT NULL,
  `data_estimada` VARCHAR(255) NOT NULL,
  `data_realizada` VARCHAR(255) NOT NULL,
  `estagio_idEstagio` INT NOT NULL,
  `relatorio` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idRelatorios`),
  CONSTRAINT `fk_Relatorios_Estagio1`
    FOREIGN KEY (`Estagio_idEstagio`)
    REFERENCES `Estagio` (`idEstagio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Relatorios_Estagio1_idx` ON `Relatorios` (`Estagio_idEstagio` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
